import {mkdtempSync,writeFileSync} from 'node:fs';import {tmpdir} from 'node:os';import path from 'node:path';import {describe,expect,it} from 'vitest';import {loadCapabilityPolicy} from '../../src/privileged/capabilityPolicy.js';import {evaluatePrivilegeRequest} from '../../src/privileged/decision.js';import {NonceTracker,signPrivilegedRequest,verifyPrivilegedRequest} from '../../src/privileged/protocol.js';
const key=Buffer.alloc(32,9);
function load(c:any[]){const d=mkdtempSync(path.join(tmpdir(),'policy-')),p=path.join(d,'p.json');writeFileSync(p,JSON.stringify({schemaVersion:1,policyVersion:'x',bundles:[{id:'b',capabilities:c}]}));return loadCapabilityPolicy(p,1000)}
describe('privileged security hardening',()=>{
 it('rejects replay of a valid signed request',()=>{const n=new NonceTracker();const r=signPrivilegedRequest({machineId:'m',operation:'service.nexusMaintenanceManage',payload:{name:'nexus-agent.service',action:'status'},maintenanceContext:{transactionId:'M',reason:'x',expiresAt:2000},timestamp:1000},key);expect(()=>verifyPrivilegedRequest(r,key,n,1000)).not.toThrow();expect(()=>verifyPrivilegedRequest(r,key,n,1000)).toThrow(/replayed/)});
 it('rejects requests outside timestamp skew',()=>{const r=signPrivilegedRequest({machineId:'m',operation:'service.nexusMaintenanceManage',payload:{name:'nexus-agent.service',action:'status'},timestamp:1000},key);expect(()=>verifyPrivilegedRequest(r,key,new NonceTracker(),62001)).toThrow(/timestamp/)});
 it('rejects missing machine capability despite valid maintenance transaction',()=>{const p=load([{id:'x',operation:'deployment.nexusMaintenancePromoteVerified',riskClass:'GOVERNED',requiredMachineCapability:'HOST_PERMISSIONS',requireMaintenanceTransaction:true}]);expect(evaluatePrivilegeRequest(p,{machineId:'m',operation:'deployment.nexusMaintenancePromoteVerified',payload:{},now:1000},{machineCapabilities:new Set(),logresLease:null,maintenanceTransaction:{transactionId:'M',reason:'x',expiresAt:2000}}).allowed).toBe(false)});
 it('rejects duplicate privileged operation mappings at policy load',()=>expect(()=>load([{id:'a',operation:'x.y',riskClass:'AUTO',requiredMachineCapability:'HOST_PERMISSIONS'},{id:'b',operation:'x.y',riskClass:'AUTO',requiredMachineCapability:'HOST_PERMISSIONS'}])).toThrow(/duplicate operation/));
});
