export interface EvidencePacket { projectId:string; canonicalSha:string; brainEpoch:number; dependencies:Record<string,string[]>; leases:string[]; claims:string[]; attempts:{taskId:string;fingerprint:string;outcome:string}[]; verificationReceipts:{sha:string;surfaces:string[];passed:boolean}[]; resources:ResourceBudget; operatorEpoch:number }
export interface ResourceBudget { workerSlots:number; cpu:number; memoryGb:number; heavyE2eSlots:number; deviceSlots:number; integrationWriters:number }
export interface RuntimeObservation { projectId:string; expectedSha:string; observedSha:string; servicesHealthy:boolean; schedulerHealthy:boolean; verificationHealthy:boolean; integrationHealthy:boolean; leasesSane:boolean; claimsSane:boolean }
export interface ProjectAdapter { projectId:string; milestone():string; canonicalSha():Promise<string>; evidence():Promise<EvidencePacket>; observe():Promise<RuntimeObservation> }
const nonneg=(n:number)=>Number.isInteger(n)&&n>=0;
export function validateBudget(b:ResourceBudget){return nonneg(b.workerSlots)&&Number.isFinite(b.cpu)&&b.cpu>0&&Number.isFinite(b.memoryGb)&&b.memoryGb>0&&nonneg(b.heavyE2eSlots)&&nonneg(b.deviceSlots)&&b.integrationWriters===1&&b.heavyE2eSlots<=b.workerSlots&&b.deviceSlots<=b.workerSlots}
export function reconcileRuntime(o:RuntimeObservation){const mismatches:string[]=[];if(!o.projectId)mismatches.push('project-id');if(!o.expectedSha||o.expectedSha!==o.observedSha)mismatches.push('runtime-sha');if(!o.servicesHealthy)mismatches.push('services');if(!o.schedulerHealthy)mismatches.push('scheduler');if(!o.verificationHealthy)mismatches.push('verification-authority');if(!o.integrationHealthy)mismatches.push('integration-authority');if(!o.leasesSane)mismatches.push('leases');if(!o.claimsSane)mismatches.push('claims');return {ok:mismatches.length===0,mismatches};}
export function minimumBlockerCut(target:string,deps:Record<string,string[]>,done:Set<string>){if(!target)throw new Error('target required');const out=new Set<string>(),visiting=new Set<string>(),seen=new Set<string>();const visit=(n:string)=>{if(visiting.has(n))throw new Error(`dependency cycle at ${n}`);if(seen.has(n))return;visiting.add(n);for(const d of deps[n]??[]){if(done.has(d))continue;const children=(deps[d]??[]).filter(x=>!done.has(x));if(children.length===0)out.add(d);else visit(d)}visiting.delete(n);seen.add(n)};visit(target);return [...out].sort();}
export function stageReceipt(stage:string,artifact:string,expectedDurationMs:number,now=Date.now()){if(!stage||!artifact||!Number.isFinite(expectedDurationMs)||expectedDurationMs<0||!Number.isFinite(now))throw new Error('invalid stage receipt');return {stage,heartbeatAt:now,artifact,expectedDurationMs};}
export function staleStage(r:{heartbeatAt:number;expectedDurationMs:number},now=Date.now(),factor=2){if(!Number.isFinite(r.heartbeatAt)||!Number.isFinite(r.expectedDurationMs)||r.expectedDurationMs<0||!Number.isFinite(now)||!Number.isFinite(factor)||factor<=0)return true;return now-r.heartbeatAt>Math.max(1000,r.expectedDurationMs*factor)}
export class OutcomeHistory { private rows:{capability:string;success:boolean;durationMs:number}[]=[]; record(capability:string,success:boolean,durationMs:number){if(!capability||!Number.isFinite(durationMs)||durationMs<0)throw new Error('invalid outcome');this.rows.push({capability,success,durationMs})} stats(capability:string){const x=this.rows.filter(r=>r.capability===capability);return {attempts:x.length,successRate:x.length?x.filter(r=>r.success).length/x.length:0,meanDurationMs:x.length?x.reduce((a,r)=>a+r.durationMs,0)/x.length:null}} }
export function completionEligible(o:RuntimeObservation,authoritiesIndependent:boolean,verificationPassed:boolean){return authoritiesIndependent===true&&verificationPassed===true&&reconcileRuntime(o).ok}
