import { createHash } from 'node:crypto';
export type Risk='low'|'medium'|'high';
export interface DecisionInput { id:string; priority:number; unlockValue:number; successLikelihood:number; verificationConfidence:number; expectedMinutes:number; resourceCost:number; capability:string; claimedState:string; observedState:string }
export interface DecisionReceipt extends DecisionInput { eligible:boolean; expectedVerifiedProgress:number; reconciliation:string }
const clamp=(n:number)=>Math.max(0,Math.min(1,n));
export function decide(items:DecisionInput[]):DecisionReceipt[]{return items.map(x=>{const eligible=x.claimedState===x.observedState;const evp=eligible?Math.max(0,x.unlockValue)*clamp(x.successLikelihood)*clamp(x.verificationConfidence)/(Math.max(.01,x.resourceCost)*Math.max(1,x.expectedMinutes)):0;return {...x,eligible,expectedVerifiedProgress:evp,reconciliation:eligible?'MATCH':'MISMATCH_FAIL_CLOSED'}}).sort((a,b)=>a.priority-b.priority||Number(b.eligible)-Number(a.eligible)||b.expectedVerifiedProgress-a.expectedVerifiedProgress||a.id.localeCompare(b.id));}
export function riskPlan(paths:string[],cpu=8,load=0,memoryFree=1,cap=4){const high=paths.some(p=>/^(src\/(brain|jobs|privileged|control)|deploy|scripts)\//.test(p));const low=paths.length>0&&paths.every(p=>/^(docs|assets)\//.test(p));const risk:Risk=high?'high':low?'low':'medium';const lanes=risk==='high'?['changed','focused','build','e2e','exact-sha']:risk==='medium'?['changed','focused','build','exact-sha']:['changed','focused','build'];const pressure=Math.min(Math.max(0,1-load/Math.max(1,cpu)),clamp(memoryFree));const heavySlots=Math.max(1,Math.min(cap,Math.floor(cpu/2),1+Math.floor(pressure*3)));return {risk,lanes,heavySlots};}
export function failureFingerprint(task:string,strategy:string,environment:string,failure:string){return createHash('sha256').update(JSON.stringify({task,strategy,environment,failure:failure.toLowerCase().trim().replace(/\s+/g,' ')})).digest('hex');}
export function retryDecision(prior:Set<string>,task:string,strategy:string,environment:string,failure:string,transient=false){const fingerprint=failureFingerprint(task,strategy,environment,failure);return prior.has(fingerprint)?{retry:false,fingerprint,action:'diagnose-change-one-variable'}:{retry:transient,fingerprint,action:transient?'retry-once':'diagnose'};}
export function authorityChain(builder:string,verifier:string,integrator:string,observer:string){const independent=new Set([builder,verifier,integrator,observer]).size===4;return {builder,verifier,integrator,runtimeObserver:observer,independent,eligible:independent};}
export function speculativeReceiptValid(receipt:{baseSha:string;paths:string[];independent:boolean},newBaseSha:string,changedPaths:string[]){return receipt.baseSha===newBaseSha||(receipt.independent&&!receipt.paths.some(p=>changedPaths.includes(p)));}
export function operatorIntentWins(currentEpoch:number,candidateEpoch:number){return candidateEpoch>=currentEpoch;}
